package net.sourceforge.javaqemu.model;

public enum OptionsEnumModel {
    RAMSIZE(0), DISPLAYOPTION(1), NOGRAPHICOPTION(2),
    VGAOPTION(3), FULLSCREENOPTION(4), WIN2KHACKOPTION(5),
    NOACPIOPTION(6), MACHINEOPTION(7), CPUOPTION(8),
    CDROMOPTION(9), FLOPPYDISKAOPTION(10), FLOPPYDISKBOPTION(11),
    BOOTOPTION(12), KEYBOARDOPTION(13), SOUNDHARDWAREOPTION(14),
    SMPOPTION(15), NUMA1OPTION(16), NUMA2OPTION(17), NUMA3OPTION(18),
    NUMA4OPTION(19), NUMA5OPTION(20), NUMA6OPTION(21), NUMA7OPTION(22),
    NUMA8OPTION(23), NUMA9OPTION(24), NUMA10OPTION(25), NOFRAMEOPTION(26),
    MEMORYPATHOPTION(27), MEMPREALLOC(28), NETWORKNIC1OPTION(29),
    NETWORKEXTRA1OPTION(30), NETWORKNETDEV1OPTION(31), NETWORKNIC2OPTION(32),
    NETWORKEXTRA2OPTION(33), NETWORKNETDEV2OPTION(34), NETWORKNIC3OPTION(35),
    NETWORKEXTRA3OPTION(36), NETWORKNETDEV3OPTION(37), NETWORKNIC4OPTION(38),
    NETWORKEXTRA4OPTION(39), NETWORKNETDEV4OPTION(40), NETWORKNIC5OPTION(41),
    NETWORKEXTRA5OPTION(42), NETWORKNETDEV5OPTION(43), NETWORKNIC6OPTION(44),
    NETWORKEXTRA6OPTION(45), NETWORKNETDEV6OPTION(46), NETWORKNIC7OPTION(47),
    NETWORKEXTRA7OPTION(48), NETWORKNETDEV7OPTION(49), NETWORKNIC8OPTION(50),
    NETWORKEXTRA8OPTION(51), NETWORKNETDEV8OPTION(52), NETWORKNIC9OPTION(53),
    NETWORKEXTRA9OPTION(54), NETWORKNETDEV9OPTION(55), NETWORKNIC10OPTION(56),
    NETWORKEXTRA10OPTION(57), NETWORKNETDEV10OPTION(58), RTCOPTION(59),
    NAMEOPTION(60), SNAPSHOTOPTION(61), NOFDBOOTCHKOPTION(62),
    NOHPETOPTION(63), MTDBLOCKOPTION(64), SDOPTION(65),
    PFLASHOPTION(66), MONITOROPTION(67), QMPOPTION(68),
    USBDRIVEROPTION(69), USBMOUSEOPTION(70), USBTABLETOPTION(71),
    USBWACOMTABLETOPTION(72), USBKEYBOARDOPTION(73), USBBRAILLEOPTION(74),
    USBDISKOPTION(75), USBSERIALOPTION(76), USBNETOPTION(77),
    KERNELBOOTOPTION(78), LPATHOPTION(79), CUSTOMOPTIONS(80);

    private final int valor;

    OptionsEnumModel(int valorOpcao) {
        valor = valorOpcao;
    }

    public int getValor() {
        return valor;
    }
}
